/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void reset_click(GButton source, GEvent event) { //_CODE_:reset_button:572639:
  myCA.reset();
} //_CODE_:reset_button:572639:

public void play_click(GButton source, GEvent event) { //_CODE_:play_button:740891:
  play=true;
} //_CODE_:play_button:740891:

public void stop_click(GButton source, GEvent event) { //_CODE_:stop_button:642813:
  play=false;
} //_CODE_:stop_button:642813:

public void scale_change(GSlider source, GEvent event) { //_CODE_:scaleslider:203195:
  sliderlabel.setText(scaleslider.getValueS());
  cellsize=scaleslider.getValueF();
} //_CODE_:scaleslider:203195:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Sketch Window");
  reset_button = new GButton(this, 508, 745, 80, 30);
  reset_button.setText("Reset");
  reset_button.setTextBold();
  reset_button.addEventHandler(this, "reset_click");
  play_button = new GButton(this, 191, 752, 80, 30);
  play_button.setText("Play");
  play_button.setTextBold();
  play_button.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  play_button.addEventHandler(this, "play_click");
  stop_button = new GButton(this, 360, 753, 80, 30);
  stop_button.setText("Stop");
  stop_button.setTextBold();
  stop_button.setLocalColorScheme(GCScheme.RED_SCHEME);
  stop_button.addEventHandler(this, "stop_click");
  genlabel = new GLabel(this, 55, 737, 80, 45);
  genlabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  genlabel.setText("Gen");
  genlabel.setTextBold();
  genlabel.setOpaque(false);
  scaleslider = new GSlider(this, 654, 740, 100, 40, 10.0);
  scaleslider.setLimits(0.5, 0.0, 1.0);
  scaleslider.setNumberFormat(G4P.DECIMAL, 2);
  scaleslider.setOpaque(false);
  scaleslider.addEventHandler(this, "scale_change");
  sliderlabel = new GLabel(this, 664, 729, 80, 20);
  sliderlabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  sliderlabel.setText("My label");
  sliderlabel.setOpaque(false);
}

// Variable declarations 
// autogenerated do not edit
GButton reset_button; 
GButton play_button; 
GButton stop_button; 
GLabel genlabel; 
GSlider scaleslider; 
GLabel sliderlabel; 